---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template Dockerfile
      slurp:
        src: /opt/my_minidlna/docker/Dockerfile
      register: dockerfile_file
      failed_when:
        not dockerfile_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          FROM alpine:3.12

          MAINTAINER borisskert <boris.skert@gmail.com>

          RUN apk --no-cache --no-progress upgrade && \
              apk --no-cache --no-progress add \
                  minidlna~=1.2.1

          EXPOSE 1900/udp 8200

          ENTRYPOINT [ "/entrypoint.sh" ]

    - name: Should create docker entrypoint
      slurp:
        src: /opt/my_minidlna/docker/entrypoint.sh
      register: docker_entrypoint_file
      failed_when:
        not docker_entrypoint_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          #!/bin/sh

          exec /usr/sbin/minidlnad -S

    - name: Should create systemd unit file
      slurp:
        src: /etc/systemd/system/minidlna.service
      register: systemd_unit_file
      failed_when:
        not systemd_unit_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          [Install]
          WantedBy=multi-user.target

          [Unit]
          Description=minidlna service
          After=docker.service
          Requires=docker.service

          [Service]
          ExecStartPre=-/usr/bin/docker rm -f minidlna.service
          ExecStartPre=/usr/bin/docker build \
            --cache-from local/minidlna:latest \
            --tag local/minidlna:latest \
            /opt/my_minidlna/docker

          ExecStart=/usr/bin/docker run --name minidlna.service \
            --net=host \
            --volume /srv/my_minidlna/config/minidlna.conf:/etc/minidlna.conf:ro \
            --volume /srv/my_minidlna/media/music:/opt/Music:ro \
            --volume /srv/my_minidlna/media/videos:/opt/Videos:ro \
            --volume /srv/my_minidlna/media/pictures:/opt/Pictures:ro \
            local/minidlna:latest

          ExecStop=/usr/bin/docker stop minidlna.service
          ExecStopPost=-/usr/bin/docker rm -f minidlna.service

          Restart=always
          RestartSec=60s
          TimeoutSec=3600

    - name: Should create minidlna config file
      slurp:
        src: /srv/my_minidlna/config/minidlna.conf
      register: minidlna_config_file
      failed_when:
        not minidlna_config_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          port=8200

          media_dir=A,/opt/Music
          media_dir=V,/opt/Videos
          media_dir=P,/opt/Pictures

          album_art_names=Cover.jpg/cover.jpg/AlbumArtSmall.jpg/albumartsmall.jpg/AlbumArt.jpg/albumart.jpg/Album.jpg/album.jpg/Folder.jpg/folder.jpg/Thumb.jpg/thumb.jpg

          inotify=yes

          enable_tivo=no

          tivo_discovery=bonjour

          strict_dlna=no

          notify_interval=900

          serial=12345678
          model_number=1
