---
- name: Verify
  hosts: all
  become: true

  tasks:
    - name: Should template Dockerfile
      slurp:
        src: /opt/minidlna/docker/Dockerfile
      register: dockerfile_file
      failed_when:
        not dockerfile_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          FROM alpine:3.12

          MAINTAINER borisskert <boris.skert@gmail.com>

          RUN apk --no-cache --no-progress upgrade && \
              apk --no-cache --no-progress add \
                  minidlna

          EXPOSE 1900/udp 8200

          ENTRYPOINT [ "/entrypoint.sh" ]

    - name: Should create docker entrypoint
      slurp:
        src: /opt/minidlna/docker/entrypoint.sh
      register: docker_entrypoint_file
      failed_when:
        not docker_entrypoint_file.content == ( expected_content | b64encode )
      vars:
        expected_content: |
          #!/bin/sh

          exec /usr/sbin/minidlnad -S
